### ISSUE TITLE
Login-Bestätigung bei fehlerhafter Projekt ID

### ISSUE THREAD

**Issue by siremp** [onetask-ai/onetask-python#2]
Bei fehlerhafter Projekt ID kriege ich positives LogIn-Feedback

![image](https://user-images.githubusercontent.com/70139038/129044887-01b9e5bf-7274-4808-a296-d94f30809e5c.png)

**Comment by elangenhan** [comment]
Login ist natürlich erfolgreich. Vermutlich sollte eine zweite Meldung folgen, dass die ProjektID inkorrekt ist

**Comment by elangenhan** [comment]
Unser Login kennt keine Projekte und die sollte er auch nicht kennen. Er überprüft nur Login Daten und sagt jo oder nope
